### ISSUE TITLE
Feature: lookup tables

### ISSUE THREAD

**Issue by chasm** [site-bender/operations#16]
We need to be able to take a value, then look up a value in a lookup table.

For example, the lookup table might say:

- Up to 100, then 1%
- Up to 500, then 5%
- Up to 1000, then 7%
Etc.

So if I provide a value of 75, I get back 1%. If I send 750, I get back 7%.

**Comment by chasm** [comment]
@benjstephenson Are you satisfied with this?

**Comment by benjstephenson** [comment]
I think so yeah.  The current implementation should let us do this example 👍
